# Generated by Django 5.2.7 on 2026-09-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('anomaly_type', models.CharField(choices=[('CONTINUOUS_FLOW', 'Continuous flow'), ('HIGH_FLOW', 'High flow'), ('READING_GAP', 'Reading gap'), ('INVALID_READING', 'Invalid reading')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=12)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='fleet.device')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['device', 'start_time'], name='anomaly_device_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gte', models.F('start_time')), _connector='OR'), name='anomaly_end_after_start'), models.UniqueConstraint(fields=('device', 'start_time', 'anomaly_type'), name='unique_device_anomaly_start_type')],
            },
        ),
    ]
