# Generated by Django 5.2.7 on 2026-09-22 09:54

import django.db.models.deletion
import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[fleet.models.validate_iana_timezone])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('WATER_METER', 'Water meter'), ('FLOW_SENSOR', 'Flow sensor')], default='WATER_METER', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('installed_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='fleet.site')),
            ],
            options={
                'ordering': ['site__name', 'name'],
                'indexes': [models.Index(fields=['site', 'status'], name='device_site_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('last_seen_at__isnull', True), ('last_seen_at__gte', models.F('installed_at')), _connector='OR'), name='device_last_seen_after_install')],
            },
        ),
    ]
