# Generated by Django 5.2.7 on 2026-09-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('flow_rate_lpm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cumulative_volume_l', models.DecimalField(decimal_places=3, max_digits=16)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('signal_strength', models.SmallIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='fleet.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='reading_device_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'timestamp'), name='unique_device_reading_timestamp'), models.CheckConstraint(condition=models.Q(('flow_rate_lpm__gte', 0)), name='reading_flow_nonnegative'), models.CheckConstraint(condition=models.Q(('cumulative_volume_l__gte', 0)), name='reading_volume_nonnegative'), models.CheckConstraint(condition=models.Q(('battery_voltage__isnull', True), ('battery_voltage__gte', 0), _connector='OR'), name='reading_battery_nonnegative')],
            },
        ),
    ]
